import './globals.css'
import { Inter } from 'next/font/google'
import Header from './src/components/Header'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  
  return (
    <html  lang="en">
      
      <body className={inter.className}><div className='bg-slate-300'><Header></Header>{children}</div></body>
    </html>
  )
}
